package fr.laforge.benoist.financialmanager.domain.model.notification

import java.util.UUID

/**
 * A user-defined template for parsing a bank or payment notification.
 *
 * The [pattern] uses two reserved placeholders:
 * - `{amount}` — marks where the monetary amount appears in the notification body.
 * - `{description}` — marks where the merchant/transaction description appears.
 * - All other text is treated as a literal separator that must be present.
 *
 * Example: `"{amount} € {description}"` matches `"10,00 € Amazon"`
 *
 * @property id         Unique identifier, auto-generated by default.
 * @property description Human-readable label shown in the Settings UI (e.g. "My bank SMS").
 * @property pattern    Placeholder-based format string used to extract [amount] and [description].
 */
data class NotificationFormat(
    val id: UUID = UUID.randomUUID(),
    val description: String,
    val pattern: String,
)
