package fr.laforge.benoist.financialmanager.domain.model.notification

import java.util.UUID

/**
 * Designates where the transaction description should be sourced when parsing a notification.
 *
 * - [BODY]: extract the description from the notification body using the `{description}`
 *   placeholder in the pattern. Falls back to the notification title if the placeholder
 *   is absent from the pattern.
 * - [TITLE]: always use the notification title as the description, regardless of whether
 *   `{description}` appears in the pattern. Useful when the body carries no merchant
 *   information but the app name or sender is the meaningful label.
 */
enum class DescriptionSource { BODY, TITLE }

/**
 * A user-defined template for parsing a bank or payment notification.
 *
 * The [pattern] uses two reserved placeholders:
 * - `{amount}` — (required) marks where the monetary amount appears in the notification body.
 * - `{description}` — (optional) marks where the merchant/transaction description appears
 *   in the body. Relevant only when [descriptionSource] is [DescriptionSource.BODY].
 * - All other text is treated as a literal separator that must be present.
 *
 * Example: `"{amount} € {description}"` with [DescriptionSource.BODY] matches `"10,00 € Amazon"`.
 * Example: `"{amount} €"` with [DescriptionSource.TITLE] uses the notification title directly.
 *
 * @property id                Unique identifier, auto-generated by default.
 * @property description       Human-readable label shown in the Settings UI (e.g. "My bank SMS").
 * @property pattern           Placeholder-based format string used to extract [amount] and
 *   optionally the description from the notification body.
 * @property descriptionSource Where to read the transaction description from.
 *   Defaults to [DescriptionSource.BODY] to preserve backwards-compatibility with formats
 *   created before this field was introduced.
 */
data class NotificationFormat(
    val id: UUID = UUID.randomUUID(),
    val description: String,
    val pattern: String,
    val descriptionSource: DescriptionSource = DescriptionSource.BODY,
)
